apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |

    server {
      listen 80;
      index index.html index.php;

      root /usr/share/nginx/html;

      rewrite ^/google$  http://google.com permanent;
    }
